"""insert your copyright here.

# see the URL below for information on how to write OpenStudio measures
# http://nrel.github.io/OpenStudio-user-documentation/reference/measure_writing_guide/
"""

import typing
import openstudio
import pandas as pd
import numpy as np
import os

class ModifyStochasticFilePython(openstudio.measure.ModelMeasure):
    """A ModelMeasure."""

    def name(self):
        """Returns the human readable name.

        Measure name should be the title case of the class name.
        The measure name is the first contact a user has with the measure;
        it is also shared throughout the measure workflow, visible in the OpenStudio Application,
        PAT, Server Management Consoles, and in output reports.
        As such, measure names should clearly describe the measure's function,
        while remaining general in nature
        """
        return "Modify stochastic file using a python measure."

    def description(self):
        """Human readable description.

        The measure description is intended for a general audience and should not assume
        that the reader is familiar with the design and construction practices suggested by the measure.
        """
        return "This measure aims at modifying the stochastic csv file generated by the measure BuildResidentialScheduleFile from OpenStudio-HPXML workflow. The idea is to consider new stochastic profiles generated from models more representative of other regions. "

    def modeler_description(self):
        """Human readable description of modeling approach.

        The modeler description is intended for the energy modeler using the measure.
        It should explain the measure's intent, and include any requirements about
        how the baseline model must be set up, major assumptions made by the measure,
        and relevant citations or references to applicable modeling resources
        """
        return "Idem description"

    def arguments(self, model: typing.Optional[openstudio.model.Model] = None):
        """Prepares user arguments for the measure.

        Measure arguments define which -- if any -- input parameters the user may set before running the measure.
        """
        args = openstudio.measure.OSArgumentVector()

        csv_path_stochastic = openstudio.measure.OSArgument.makeStringArgument("csv_path_stochastic", True)
        csv_path_stochastic.setDisplayName("Path to the stochastic CSV file.")
        csv_path_stochastic.setDescription("Path to the stochastic CSV file that will be modified by this measure.")
        csv_path_stochastic.setDefaultValue("stochastic.csv")

        args.append(csv_path_stochastic)

        csv_path_spa = openstudio.measure.OSArgument.makeStringArgument("csv_path_spa", True)
        csv_path_spa.setDisplayName("Path to the spa CSV file.")
        csv_path_spa.setDescription("Path to the spa CSV file that will help modify the stochastic.csv file.")
        csv_path_spa.setDefaultValue("stochastic_profile_spa_W.csv")

        args.append(csv_path_spa)
        
        csv_path_pool_heater = openstudio.measure.OSArgument.makeStringArgument("csv_path_pool_heater", True)
        csv_path_pool_heater.setDisplayName("Path to the pool heater CSV file.")
        csv_path_pool_heater.setDescription("Path to the pool heater CSV file that will help modify the stochastic.csv file.")
        csv_path_pool_heater.setDefaultValue("stochastic_profile_pool_heater_W.csv")

        args.append(csv_path_pool_heater)
        
        csv_path_pool_pump = openstudio.measure.OSArgument.makeStringArgument("csv_path_pool_pump", True)
        csv_path_pool_pump.setDisplayName("Path to the pool pump CSV file.")
        csv_path_pool_pump.setDescription("Path to the pool pump CSV file that will help modify the stochastic.csv file.")
        csv_path_pool_pump.setDefaultValue("stochastic_profile_pool_pump_W.csv")

        args.append(csv_path_pool_pump)
        
        csv_path_ev = openstudio.measure.OSArgument.makeStringArgument("csv_path_ev", True)
        csv_path_ev.setDisplayName("Path to the EV CSV file.")
        csv_path_ev.setDescription("Path to the EV CSV file that will help modify the stochastic.csv file.")
        csv_path_ev.setDefaultValue("stochastic_profile_ev_W.csv")

        args.append(csv_path_ev)
        
        csv_path_heating_setpoint = openstudio.measure.OSArgument.makeStringArgument("csv_path_heating_setpoint", True)
        csv_path_heating_setpoint.setDisplayName("Path to the heating setpoint CSV file.")
        csv_path_heating_setpoint.setDescription("Path to the heating setpoint CSV file that will help modify the stochastic.csv file.")
        csv_path_heating_setpoint.setDefaultValue("stochastic_profile_heating_setpoint.csv")

        args.append(csv_path_heating_setpoint)

        results_dir = openstudio.measure.OSArgument.makeStringArgument("results_dir", True)
        results_dir.setDisplayName("Path to the results directory.")
        results_dir.setDescription("Path to the directory where the results will be saved.")
        results_dir.setDefaultValue("results")

        args.append(results_dir)

        spa_presence = openstudio.measure.OSArgument.makeBoolArgument("spa_presence", True)
        spa_presence.setDisplayName("Presence of spa")
        spa_presence.setDescription("Indicates whether a spa is present.")
        spa_presence.setDefaultValue(False)

        args.append(spa_presence)
        
        pool_presence = openstudio.measure.OSArgument.makeBoolArgument("pool_presence", True)
        pool_presence.setDisplayName("Presence of pool")
        pool_presence.setDescription("Indicates whether a pool is present.")
        pool_presence.setDefaultValue(False)

        args.append(pool_presence)
        
        pool_heater_type = openstudio.measure.OSArgument.makeStringArgument("pool_heater_type", True)
        pool_heater_type.setDisplayName("Pool Heater Type")
        pool_heater_type.setDescription("Type of the pool heater.")
        pool_heater_type.setDefaultValue("none")

        args.append(pool_heater_type)
        
        ev_presence = openstudio.measure.OSArgument.makeBoolArgument("ev_presence", True)
        ev_presence.setDisplayName("Presence of EV")
        ev_presence.setDescription("Indicates whether electric vehicle(s) is(are) present.")
        ev_presence.setDefaultValue(False)

        args.append(ev_presence)
        
        stochastic_heating_setpoint = openstudio.measure.OSArgument.makeBoolArgument("stochastic_heating_setpoint", True)
        stochastic_heating_setpoint.setDisplayName("Stochastic Heating Setpoint")
        stochastic_heating_setpoint.setDescription("Indicates whether a stochastic heating setpoint profile is used.")
        stochastic_heating_setpoint.setDefaultValue(False)

        args.append(stochastic_heating_setpoint)

        building_id = openstudio.measure.OSArgument.makeStringArgument("building_id", True)
        building_id.setDisplayName("Building ID")
        building_id.setDescription("Unique identifier for the building.")
        building_id.setDefaultValue("Building_Unknown")

        args.append(building_id)

        timestep = openstudio.measure.OSArgument.makeDoubleArgument("timestep", True)
        timestep.setDisplayName("Timestep")
        timestep.setDescription("Timestep of the simulation.")
        timestep.setDefaultValue(15.0)
        
        args.append(timestep)

        return args

    def run(
        self,
        model: openstudio.model.Model,
        runner: openstudio.measure.OSRunner,
        user_arguments: openstudio.measure.OSArgumentMap,
    ):
        """Defines what happens when the measure is run."""
        super().run(model, runner, user_arguments)  # Do **NOT** remove this line

        if not (runner.validateUserArguments(self.arguments(model), user_arguments)):
            return False

        csv_path_stochastic = runner.getStringArgumentValue("csv_path_stochastic", user_arguments)
        csv_path_spa = runner.getStringArgumentValue("csv_path_spa", user_arguments)
        csv_path_pool_heater = runner.getStringArgumentValue("csv_path_pool_heater", user_arguments)
        csv_path_pool_pump = runner.getStringArgumentValue("csv_path_pool_pump", user_arguments)
        csv_path_ev = runner.getStringArgumentValue("csv_path_ev", user_arguments)
        csv_path_heating_setpoint = runner.getStringArgumentValue("csv_path_heating_setpoint", user_arguments)
        results_dir = runner.getStringArgumentValue("results_dir", user_arguments)
        spa_presence = runner.getBoolArgumentValue("spa_presence", user_arguments)
        pool_presence = runner.getBoolArgumentValue("pool_presence", user_arguments)
        pool_heater_type = runner.getStringArgumentValue("pool_heater_type", user_arguments)
        ev_presence = runner.getBoolArgumentValue("ev_presence", user_arguments)
        stochastic_heating_setpoint = runner.getBoolArgumentValue("stochastic_heating_setpoint", user_arguments)
        building_id = runner.getStringArgumentValue("building_id", user_arguments)
        timestep = runner.getDoubleArgumentValue("timestep", user_arguments)
        
		# If it is an upgraded building, copy the stochastic.csv from the reference building
        # if "_SetOfMeasures" in building_id:
        #     # identify reference building ID
        #     ref_building_id = building_id.split("_")[0]
        #     # copy the stochastic.csv file from the reference building results folder
        #     ref_csv_path = os.path.join(results_dir, ref_building_id, "stochastic.csv")
        #     if os.path.exists(ref_csv_path):
        #         import shutil
        #         shutil.copyfile(ref_csv_path, csv_path_stochastic)
        #         runner.registerInfo(f"Copied stochastic file from reference building '{ref_building_id}' to upgraded building '{building_id}'.")	
        #     else:
        #         runner.registerError(f"Reference stochastic file '{ref_csv_path}' does not exist for building '{ref_building_id}'.")
        #         return False

        # check if the stochastic.csv file exists
        if not os.path.exists(csv_path_stochastic):
            runner.registerError(f"CSV file '{csv_path_stochastic}' does not exist.")
            return False

        # read the CSV file with pandas
        # Using pandas to read the CSV file allows for easier manipulation and analysis of the data.
        try:
            df = pd.read_csv(csv_path_stochastic)
        except Exception as e:
            runner.registerError(f"Failed to read CSV file '{csv_path_stochastic}': {e}")
            return False
        # create an array of simulation timesteps in minutes
        sim_timesteps_minutes = np.arange(0, df.shape[0]*timestep, timestep)
        
		######################################################
        # STOCHASTIC HEATING SETPOINT
		######################################################
        if stochastic_heating_setpoint:
            # if "_SetOfMeasures" in building_id:
			# 	# no need to modify the stochastic heating setpoint profile for upgraded buildings (keep the same as the reference building)
            #     runner.registerInfo(f"No modification of stochastic file needed for upgraded building '{building_id}'.")	
            # else:
			# load the heating setpoint profile from the provided CSV file
            try:
                heating_setpoint_profile = pd.read_csv(csv_path_heating_setpoint, usecols=['time_min','heating_setpoint_F'])
            except Exception as e:
                runner.registerError(f"Failed to read CSV file '{csv_path_heating_setpoint}': {e}")
                return False
			# forward fill the heating setpoint profile to match the simulation timestep
            idx = np.searchsorted(heating_setpoint_profile['time_min'], sim_timesteps_minutes, side='right') - 1
            idx[idx < 0] = 0  # handle out-of-bounds indices
            heating_setpoint_F = heating_setpoint_profile['heating_setpoint_F'].iloc[idx].values
			# overwrite the existing heating setpoint profile
            df['heating_setpoint'] = heating_setpoint_F	
                    
		######################################################
        # EV
		######################################################
        if ev_presence:
            # if "_SetOfMeasures" in building_id:
			# 	# no need to modify the stochastic ev profile for upgraded buildings (keep the same as the reference building)
            #     runner.registerInfo(f"No modification of stochastic file needed for upgraded building '{building_id}'.")	
            # else:
			# load the ev profile from the provided CSV file
            try:
                ev_profile = pd.read_csv(csv_path_ev)
            except Exception as e:
                runner.registerError(f"Failed to read CSV file '{csv_path_ev}': {e}")
                return False
            # interpolate the ev profile to match the simulation timestep
            ev_profile_W = np.interp(sim_timesteps_minutes,
                                     ev_profile['time_min'],
                                     ev_profile['power_W'],
                                     left=0, right=0)
            # normalize the profile to have values between 0 and 1 and overwrite the existing profile
            ev_profile_normalized = ev_profile_W / ev_profile_W.max()
            df['plug_loads_vehicle'] = ev_profile_normalized
        
		######################################################
        # SPA
		######################################################
		# perform modification to consider spa energy profiles
        if spa_presence:
            # if "_SetOfMeasures" in building_id:
			# 	# no need to modify the stochastic spa profile for upgraded buildings (keep the same as the reference building)
            #     runner.registerInfo(f"No modification of stochastic file needed for upgraded building '{building_id}'.")
            # else:
			# load the spa profile from the provided CSV file
            try:
                spa_profile = pd.read_csv(csv_path_spa)
            except Exception as e:
                runner.registerError(f"Failed to read CSV file '{csv_path_spa}': {e}")
                return False
			# interpolate the spa profile to match the simulation timestep
            sim_profile_W = np.interp(sim_timesteps_minutes,
										spa_profile['time_min'],
										spa_profile['power_W'],
										left=0, right=0)
			# normalize the profile to have values between 0 and 1 and overwrite the existing profile
            sim_profile_normalized = sim_profile_W / sim_profile_W.max()
            df['permanent_spa_pump'] = np.ones(df.shape[0]) 
            df['permanent_spa_heater'] = sim_profile_normalized
        
		######################################################
		# POOL
		######################################################
		# perform modification to consider pool energy profiles
        if pool_presence:
            # if "_SetOfMeasures" in building_id:
            #     # no need to modify the stochastic pool profile for upgraded buildings (keep the same as the reference building)
            #     runner.registerInfo(f"No modification of stochastic file needed for upgraded building '{building_id}'.")
            # else:
			# load the pool pump profile from the provided CSV file
            try:
                pool_pump_profile = pd.read_csv(csv_path_pool_pump)
            except Exception as e:
                runner.registerError(f"Failed to read CSV file '{csv_path_pool_pump}': {e}")
                return False
			# interpolate the pool pump profile to match the simulation timestep
            pool_pump_profile_W = np.interp(sim_timesteps_minutes,
											pool_pump_profile['time_min'],
											pool_pump_profile['power_W'],
											left=0, right=0)
			# normalize the profile to have values between 0 and 1 and overwrite the existing profile
            pool_pump_profile_normalized = pool_pump_profile_W / pool_pump_profile_W.max()
            df['pool_pump'] = pool_pump_profile_normalized
				
			# load the pool heater profile from the provided CSV file
            if pool_heater_type in ['electric resistance','gas fired','heat pump']:
                try:
                    pool_heater_profile = pd.read_csv(csv_path_pool_heater)
                except Exception as e:
                    runner.registerError(f"Failed to read CSV file '{csv_path_pool_heater}': {e}")
                    return False
				# interpolate the pool heater profile to match the simulation timestep
                pool_heater_profile_W = np.interp(sim_timesteps_minutes,
													pool_heater_profile['time_min'],
													pool_heater_profile['power_W'],
													left=0, right=0)
				# normalize the profile to have values between 0 and 1 and overwrite the existing profile
                pool_heater_profile_normalized = pool_heater_profile_W / pool_heater_profile_W.max()
                df['pool_heater'] = pool_heater_profile_normalized

		# write the modified dataframe back to the CSV file
        try:
            df.to_csv(csv_path_stochastic, index=False)
        except Exception as e:
            runner.registerError(f"Failed to write CSV file '{csv_path_stochastic}': {e}")
            return False

        # report success
        runner.registerInfo(f"Successfully modified the stochastic file at '{csv_path_stochastic}'.")

        return True

# register the measure to be used by the application
ModifyStochasticFilePython().registerWithApplication()
